# Generated by Django 3.1.7 on 2021-04-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20210408_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='time',
        ),
    ]
