# Generated by Django 3.1.7 on 2021-04-06 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='customer_image/'),
            preserve_default=False,
        ),
    ]
